# This workflow will install Divio CLI and deploy a local project into the Divio cloud

name: Divio Continuous Deployment

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    env:
      DIVIO_API_TOKEN: ${{ secrets.DIVIO_API_TOKEN }}
      DIVIO_PROJECT_ID: ${{ secrets.DIVIO_PROJECT_ID }}   

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Divio CLI
      run: |
        python -m pip install --upgrade pip
        pip install divio-cli
    - name: Deploy to Divio Cloud
      run: |
        divio login "$DIVIO_API_TOKEN"
        divio project deploy --remote-id "$DIVIO_PROJECT_ID"
  