# This workflow will install Django Axes Application into the Django Project, build and Deploy the project into Divio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django Axes application

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Django Axes Application
      run: |
        docker-compose build
        docker-compose run web python manage.py migrate
    - name: Deploy to Divio
      env:
        DIVIO_API_KEY: ${{ secrets.DIVIO_API_KEY }}
        DIVIO_PROJECT_NAME: ${{ secrets.DIVIO_PROJECT_NAME }}   
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        curl -X POST --data 'stage=env-DIVIO_PROJECT_NAME' --header "Authorization: Basic DIVIO_API_KEY" https://control.divio.com/api/v1/website/DIVIO_PROJECT_ID/deploy/

        # git remote add divio https://divio:$DIVIO_API_KEY@git.divio.com/$DIVIO_PROJECT_NAME.git
        # git push divio HEAD:master -f
        
