# This workflow will install Django Axes Application into the Django Project, build and Deploy the project into Divio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django Axes application

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        Python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{m matrix.python-version }}
    - uses: actions/setup-python@v1
      with:
        python-version: ${{m matrix.python-version }}
    - name: Install Divio CLI
      run: |
        python -m pip install --upgrade pip
        pip install divio-cli
    - name: Set Divio Credentials 
      env:
        DIVIO_API_KEY: ${{ secrets.DIVIO_API_KEY }}
        DIVIO_PROJECT_NAME: ${{ secrets.DIVIO_PROJECT_NAME }}   
      run: |
        divio login DIVIO_API_KEY
 #       git push divio HEAD:master -f
        
    - name: Install Django Axes Application
      run: |
        docker-compose build
        docker-compose run web python manage.py migrate
