# This workflow will install Divio CLI and deploy a Django Axes Application into the Divio cloud

name: Divio Continuous Deployment

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    env:
      DIVIO_API_TOKEN: ${{ secrets.DIVIO_API_TOKEN }}
      DIVIO_PROJECT_ID: ${{ secrets.DIVIO_PROJECT_ID }}   
      DIVIO_PROJECT_SLUG: ${{ secrets.DIVIO_PROJECT_SLUG }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: assign credentials and copy .aldryn to config
      run: |
        json -I -f .aldryn \
        -e "this.DIVIO_PROJECT_ID='$(${{ secrets.DIVIO_PROJECT_ID }})'" 
        -e "this.DIVIO_PROJECT_PLUG='$(${{ secrets.DIVIO_PROJECT_PLUG }})'" 
        cp .aldryn config
    - name: Install Divio CLI
      run: |
        python -m pip install --upgrade pip
        pip install divio-cli
    - name: Deploy to Divio Cloud
      run: |
        divio login "$DIVIO_API_TOKEN"
        divio project deploy
  # Create the deleted Divio cli config file
    - name: Replace back .aldryn
      run: |
        cp config .aldryn
        rm -rf config
